language: node_js
node_js:
  - "0.10"
  
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/30b8d259b2da98f68659
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
